default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 1305438asep
  database: register_app_db
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: register_app_db
